window.DGCV_CONTENT = {
  "es": {
    "general": "# Contenido general\n\n## Navegación\n- Licenciatura\n- Investigación\n- Interacción\n- Posgrado\n- Contacto\n\n## Botón del encabezado\nQuiero estudiar diseño gráfico\n\n## Nombre institucional\nDiseño Gráfico y Comunicación Visual  \nUniversidad Mayor de San Simón\n\n## Ubicación breve\nCampus Central Las Cuadras · bloque nuevo, 3.er piso\n\n## Correo\ndirecciondgycv@umss.edu\n\n## Estado del sitio\nSitio en construcción · Primera versión\n",
    "inicio": "# Inicio\n\n## Antetítulo\nUniversidad Mayor de San Simón · Cochabamba\n\n## Titular\nDiseñamos  \n[acento]ideas[/acento] que  \n[contorno]comunican.[/contorno]\n\n## Descripción\nFormación creativa, crítica y estratégica para transformar mensajes en experiencias visuales que conectan con las personas.\n\n## Misión\nFormar profesionales en Diseño Gráfico y Comunicación Visual con bases científicas, tecnológicas, humanísticas y éticas, capaces de responder a las necesidades de la sociedad.\n\n## Visión\nSer una carrera referente en la formación, investigación e interacción social del diseño y la comunicación visual.\n\n## Objetivos\nImpulsar una formación crítica y creativa que aporte al desarrollo cultural, social y productivo del país.\n\n## Botón\nConoce  \nla carrera\n\n## Cinta\n- Identidad visual\n- Diseño editorial\n- Medios digitales\n- Comunicación estratégica\n",
    "licenciatura": "# Licenciatura\n\n## Etiqueta\nLicenciatura\n\n## Titular\nFormación para  \ntransformar ideas.\n\n## Qué es la carrera\nDiseño Gráfico y Comunicación Visual es una carrera de cinco años orientada a la creación de soluciones visuales pertinentes para las necesidades de la sociedad.\n\n## Qué hace la carrera\nIntegra diseño, comunicación, tecnología, investigación y cultura para desarrollar proyectos en medios impresos, digitales, audiovisuales y espaciales.\n\n## Modalidades de admisión\nLa información y las convocatorias de ingreso se publican mediante los canales oficiales de la Universidad Mayor de San Simón.\n\n## Modalidades de titulación\nEl plan académico contempla la modalidad de graduación mediante proyecto de grado.\n\n## Datos\n- 2008 | Creación del programa\n- 5 | Años de formación\n- 29 | Asignaturas\n- 6.050 | Horas académicas\n",
    "investigacion": "# Investigación\n\n## Etiqueta\nInvestigación\n\n## Titular\nDiseñar también  \nes investigar.\n\n## Introducción\nLa investigación fortalece la producción de conocimiento y permite comprender los problemas de comunicación visual desde el contexto.\n\n## Investigación formal\nProyectos desarrollados con métodos y objetivos definidos para aportar nuevo conocimiento al campo del diseño y la comunicación visual.\n\n## Investigación formativa\nProcesos realizados en asignaturas y talleres para que estudiantes aprendan a observar, preguntar, documentar y fundamentar sus decisiones.\n\n## Investigación de la carrera\nEspacio para publicar líneas, proyectos, resultados y equipos de investigación de la carrera.\n\n## Investigación del CIDIS\nEspacio para vincular y difundir la producción del Centro de Investigación en Diseño.\n",
    "interaccion": "# Interacción\n\n## Etiqueta\nInteracción\n\n## Titular\nAprender haciendo  \ncon la comunidad.\n\n## Prácticas preprofesionales\nLas prácticas acercan a estudiantes al ejercicio profesional y a contextos reales de trabajo, colaboración y servicio.\n\n## Laboratorio\nUn espacio para experimentar, producir y desarrollar proyectos que conecten la formación académica con necesidades concretas.\n",
    "posgrado": "# Posgrado\n\n## Etiqueta\nPosgrado\n\n## Titular\nSeguir aprendiendo.  \nSeguir diseñando.\n\n## Oferta de diplomados\nEn esta sección se publicará la oferta vigente de programas de diplomado y formación continua vinculados al diseño y la comunicación visual.\n\n## Estado\nConsulta próximamente las convocatorias y fechas disponibles.\n",
    "contacto": "# Contacto\n\n## Etiqueta\nContacto\n\n## Titular\nConversemos.\n\n## Descripción\nLa carrera funciona en el Campus Central Las Cuadras, final Jordán, en el bloque nuevo de la Facultad de Arquitectura y Ciencias del Hábitat.\n\n## Redes sociales\nPróximamente se publicarán aquí los enlaces oficiales de la carrera.\n\n## Número\nNúmero institucional por confirmar.\n\n## Correo\ndirecciondgycv@umss.edu\n"
  },
  "qu": {
    "general": "# Tukuy qillqasqa\n\n## Navegación\n- Licenciatura\n- Yachay mask'ay\n- Llaqtawan llamk'ay\n- Qhipa yachay\n- Rimanakuy\n\n## Botón del encabezado\nDiseño gráficota yachakuyta munani\n\n## Nombre institucional\nDiseño Gráfico y Comunicación Visual  \nUniversidad Mayor de San Simón\n\n## Ubicación breve\nLas Cuadras chawpi campuspi · musuq wasi, kimsa ñiqin pata\n\n## Correo\ndirecciondgycv@umss.edu\n\n## Estado del sitio\nWeb nisqa ruwakuchkan · Ñawpaq rikuchiy\n",
    "inicio": "# Qallariy\n\n## Antetítulo\nUniversidad Mayor de San Simón · Quchapampa\n\n## Titular\nYuyaykunata  \nrikuchinapaq  \nruwayku.\n\n## Descripción\nYuyaykunata runakunawan tinkuchiq rikuna willaykunaman tikranapaq, kamay, allin yuyaywan qhawariy, imaymana ñan mask'ay ima yachachiy.\n\n## Misión\nCiencia, tecnología, runa kaynin, ética ima saphiwan Diseño Gráfico y Comunicación Visualpi profesionales nisqakunata wakichiy; paykunaqa llaqtap munasqankunaman kutichiyta atinqanku.\n\n## Visión\nDiseño nisqapi, rikuna willaypi, yachay mask'aypi, llaqtawan llamk'aypi ima ñawpaq riq carrera kay.\n\n## Objetivos\nSuyup cultura, llaqta, ruway miraypaq allin yuyayniyuq, kamaq yachachiyta kallpachay.\n\n## Botón\nCarrerata  \nriqsiy\n\n## Cinta\n- Rikuna identidad\n- Editorial diseño\n- Digital medios\n- Willay wakichiy\n",
    "licenciatura": "# Licenciatura\n\n## Etiqueta\nLicenciatura\n\n## Titular\nYuyaykunata  \ntikranapaq yachay.\n\n## Qué es la carrera\nDiseño Gráfico y Comunicación Visualqa phichqa wata yachakuna carrera. Llaqtap munasqanman jina rikuna willaykunata allinchanapaq wakichisqa.\n\n## Qué hace la carrera\nDiseño, willay, tecnología, yachay mask'ay, cultura ima huñuspa imprenta, digital, audiovisual, espacio mediospi proyectos nisqakunata ruwan.\n\n## Modalidades de admisión\nYaykunapaq willaykuna, waqyaykuna ima Universidad Mayor de San Simónpa canales oficiales nisqankunapi lluqsichisqa kanku.\n\n## Modalidades de titulación\nYachay planqa proyecto de grado nisqawan tukuchiyta qhawarin.\n\n## Datos\n- 2008 | Programa paqarisqan\n- 5 | Yachakuy watakuna\n- 29 | Yachachina wakichiykuna\n- 6.050 | Yachakuy uraskuna\n",
    "investigacion": "# Yachay mask'ay\n\n## Etiqueta\nYachay mask'ay\n\n## Titular\nDiseñoyqa yachayta  \nmask'aypis kan.\n\n## Introducción\nYachay mask'ayqa musuq yachayta paqarichin, rikuna willay sasachakuykunata kawsayninchikmanta unanchayta yanapan.\n\n## Investigación formal\nAllin wakichisqa ñankunawan, objetivos nisqakunawan ima proyectos ruwasqa; diseño, rikuna willay ima yachayninman musuq yachayta yapanapaq.\n\n## Investigación formativa\nYachachina wakichiykunapi, talleres nisqakunapi ima ruwasqa ñankuna; yachakuqkuna qhawayta, tapuyta, qillqayta, akllasqankuta yuyaywan sayachiyta yachakunankupaq.\n\n## Investigación de la carrera\nCarrerapa yachay mask'ay ñankunata, proyectos, lluqsiyninkunata, llamk'aq tantakunata ima riqsichinapaq kiti.\n\n## Investigación del CIDIS\nCentro de Investigación en Diseñopa ruwasqanta tinkuchinapaq, riqsichinapaq ima kiti.\n",
    "interaccion": "# Llaqtawan llamk'ay\n\n## Etiqueta\nLlaqtawan llamk'ay\n\n## Titular\nLlaqtawan kuska  \nruwaspa yachakuy.\n\n## Prácticas preprofesionales\nPrácticas nisqakunaqa yachakuqkunata profesión llamk'ayman, chiqap llamk'ana, yanapanakuy, servicio ima kawsaykunaman asuykachin.\n\n## Laboratorio\nYachayta llaqtap chiqap munasqankunawan tinkuchiq proyectos nisqakunata mallinapaq, ruwanapaq, wiñachinapaq ima kiti.\n",
    "posgrado": "# Qhipa yachay\n\n## Etiqueta\nQhipa yachay\n\n## Titular\nYachakuyta qatipay.  \nDiseñoyta qatipay.\n\n## Oferta de diplomados\nKay kitipi diseño, rikuna willay imawan tinkisqa diplomado programas, sapa kuti yachakuy wakichiykuna ima riqsichisqa kanqa.\n\n## Estado\nMusuq waqyaykunata, p'unchawkunata ima qhipaman qhaway.\n",
    "contacto": "# Rimanakuy\n\n## Etiqueta\nRimanakuy\n\n## Titular\nRimanakusunchik.\n\n## Descripción\nCarreraqa Las Cuadras chawpi campuspi, Jordán tukukuyninpi, Facultad de Arquitectura y Ciencias del Hábitatpa musuq wasinpi llamk'an.\n\n## Redes sociales\nKaypi carrerapa redes sociales oficiales nisqankuna qhipaman riqsichisqa kanqa.\n\n## Número\nInstituciónpa yupayninqa chiqanchanaraqmi.\n\n## Correo\ndirecciondgycv@umss.edu\n"
  }
};
